COD-20 - Input with Data Provider
faheemc93/Dunkin_Donuts pull request #19
Opened 2021-11-18 05:22 UTC by srahman09

Added two data providers in the hooks page, 1 for hot drink items and 1 for cold drink items:
![Screen Shot 2021-11-12 at 4 10 22 PM](https://user-images.githubusercontent.com/87837436/142356489-d16888f6-88cd-4bc5-a5ba-1ea7ffe9aa8e.png)

Changed menuTest to take in the data provider rather than entering each item category and item separately.
Also separated the test cases so you can test for each category (hot drinks and cold drinks) separately:
![Screen Shot 2021-11-12 at 4 12 46 PM](https://user-images.githubusercontent.com/87837436/142356615-caa34c21-fa78-440a-950e-54c5ceb5f65f.png)

2021-11-18 19:07 UTC, syedishmam approved these changes

2021-11-19 21:10 UTC, syedishmam requested changes
Menu test has an unused import for DataProvider

2021-11-19 22:12 UTC, syedishmam commented
@srahman09 you have a merge conflict

2021-11-19 22:13 UTC, syedishmam approved these changes

2021-11-20 03:42 UTC, faheemc93 approved these changes

2021-11-20 04:44 UTC, merged